services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --ssl-keyfile=/app/localhost+2-key.pem --ssl-certfile=/app/localhost+2.pem
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://api_user:api_password@db:5432/api_db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: